server:
  port: 0

spring:
  application:
    name: sender
  mail:
    host: smtp.yandex.ru
    port: 465
    username: gpussender@yandex.ru
    password: "tlepetldqmggmbmt"
    test-connection: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
    sender:
      email: gpussender@yandex.ru
      text: gpu-store
bot:
  name: GPUSBOT
  token: 5920318828:AAEoullWEvgXga-yfWLK_Ytox4VtyYcDjow

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: src/main/resources/application-debug.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        web: TRACE

outbound:
  get-product: "http://localhost:8765/api/products/%s"
  unsubscribe: "http://localhost:8765/api/clients/unsubscribe/clientId=%s&productId=%s"